// This file was generated by toolbox package [rpc](https://github.com/izvir-co/service_box).
// Editing this file manually can result in a loss of your fingers and your job :)

import { type } from "arktype"
import { route } from "@izvir/rpc";

export const AccountStatus = type("'Active'").or({ reason: type.string }).or({ at: type.string })
export type AccountStatus = typeof AccountStatus.infer

export const AuditStamp = type({ kind: "'Manual'", by: type.string }).or({ kind: "'Automated'", system: type.string })
export type AuditStamp = typeof AuditStamp.infer

export const EmptyProps = type({  })
export type EmptyProps = typeof EmptyProps.infer

export const HookedProps = type({ requestId: type.string })
export type HookedProps = typeof HookedProps.infer

export const HookedResponse = type({ ok: type.boolean })
export type HookedResponse = typeof HookedResponse.infer

export const PingResponse = type({ success: type.boolean })
export type PingResponse = typeof PingResponse.infer

export const UserRole = type("'Admin'").or("'Member'").or("'Guest'")
export type UserRole = typeof UserRole.infer

export const CreateUserProps = type({ name: type.string, email: type.string, nickname: type.string.or(type.null), role: UserRole, status: AccountStatus.or(type.null), audit: AuditStamp.or(type.null) })
export type CreateUserProps = typeof CreateUserProps.infer

export const CreateUserResponse = type({ id: type.string, name: type.string, email: type.string, role: UserRole, status: AccountStatus.or(type.null), audit: AuditStamp.or(type.null) })
export type CreateUserResponse = typeof CreateUserResponse.infer

export const GetUserProps = type({ userId: type.string, includeEmail: type.boolean.or(type.null), expectedRole: UserRole.or(type.null) })
export type GetUserProps = typeof GetUserProps.infer

export const GetUserResponse = type({ id: type.string, name: type.string, email: type.string, role: UserRole, status: AccountStatus.or(type.null), lastLogin: type.string.or(type.null) })
export type GetUserResponse = typeof GetUserResponse.infer

export const ServiceDefinitions = {
  v1: {
    createUser: route({ endpoint: "v1/create_user", input: CreateUserProps, output: CreateUserResponse }),
    getUser: route({ endpoint: "v1/get_user", input: GetUserProps, output: GetUserResponse }),
    hooked: route({ endpoint: "v1/hooked", input: HookedProps, output: HookedResponse }),
    ping: route({ endpoint: "v1/ping", input: EmptyProps, output: PingResponse }),
  },
} as const;

export type ServiceDefinitions = typeof ServiceDefinitions;